# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

filegroup(
    name = "config",
    srcs = glob(["**/*.yaml"]),
    visibility = ["//examples/llvm_autotuning:__subpackages__"],
)
